# Aliases
alias g='git'
alias ga='git add'
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gcm='git checkout master'
alias gcount='git shortlog -sn'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gl='git pull'
alias glg='git log --stat --max-count=5'
alias glgg='git log --graph --max-count=5'
alias gm='git merge'
alias gp='git push'
alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'
alias gs='git status -sb' # upgrade your git if -sb breaks for you. it's fun.
alias gss='git status -s'
alias gst='git status'
alias gup='git fetch && git rebase'
